CREATE TABLE IF NOT EXISTS User
(
    UserID VARCHAR(128) NOT NULL UNIQUE,
    Email VARCHAR(320) NOT NULL UNIQUE,
    PhoneNumber TEXT NOT NULL UNIQUE,
    Fname TEXT NOT NULL,
    Lname TEXT NOT NULL,
    Bname TEXT,
    DoB TEXT NOT NULL,
    AccountType TEXT NOT NULL DEFAULT 'user',
    img TEXT,
    Email_Confirmed BIT DEFAULT 0 NOT NULL,
    Account_Status BIT DEFAULT 0 NOT NULL, 
    PRIMARY KEY (UserID)
);

CREATE TABLE IF NOT EXISTS Password
(
    UserID VARCHAR(128) NOT NULL UNIQUE,
    Password VARCHAR(64) NOT NULL,
    Salt VARCHAR(64) NOT NULL,

    PRIMARY KEY (UserID),
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE 
);

CREATE TABLE IF NOT EXISTS Address
(
    UserID VARCHAR(128) NOT NULL UNIQUE,
    Line1 VARCHAR(128) NOT NULL,
    Line2 VARCHAR(128) NOT NULL,
    City VARCHAR(128) NOT NULL,
    Postcode VARCHAR(128) NOT NULL,
    PRIMARY KEY (UserID)
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Reviews 
(
    TargetID VARCHAR(128) NOT NULL,
    ReviewerID VARCHAR(128) NOT NULL,
    FoodID VARCHAR(128) NOT NULL,
    Review TEXT NOT NULL,
    Rating INT NOT NULL,
    Date INT NOT NULL,
    PRIMARY KEY (TARGETID, ReviewerID, FoodID, Date)
    FOREIGN KEY (TargetID) REFERENCES User(UserID) ON DELETE CASCADE
    FOREIGN KEY (ReviewerID) REFERENCES User(UserID) ON DELETE CASCADE
    FOREIGN KEY (FoodID) REFERENCES Food(FoodID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Food
(
    FoodID VARCHAR(128) NOT NULL UNIQUE,
    Title VARCHAR(128) NOT NULL,
    Desc TEXT NOT NULL,
    Price DECIMAL(10,2) NOT NULL,
    img TEXT,
    Quantity INT NOT NULL,
    BusinessID VARCHAR(128) NOT NULL,
    SDate TEXT NOT NULL,
    EDate TEXT NOT NULL,
    Status BIT DEFAULT 0 NOT NULL,
    BoughtBy VARCHAR(128),
    PRIMARY KEY (FoodID)
    FOREIGN KEY (BusinessID) REFERENCES User(UserID) ON DELETE CASCADE
)

