CREATE TABLE IF NOT EXISTS User
(
    UserID VARCHAR(128) NOT NULL UNIQUE PRIMARY KEY,
    Email VARCHAR(320),
    PhoneNumber TEXT,
    Fname TEXT NOT NULL,
    Lname TEXT NOT NULL,
    DoB TEXT NOT NULL,
    img TEXT,
    Email_Confirmed BIT DEFAULT 0 NOT NULL,
    Account_Status BIT DEFAULT 0 NOT NULL, 
    FOREIGN KEY (AddressID) REFERENCES Address(AddressID)
);

CREATE TABLE IF NOT EXISTS Business
(
    BusinessID VARCHAR(128) NOT NULL UNIQUE PRIMARY KEY,
    Bname TEXT NOT NULL,
    Email VARCHAR(320) NOT NULL UNIQUE, --Contact details for business
    PhoneNumber TEXT NOT NULL UNIQUE,
    img TEXT,
    AddressID VARCHAR(128) NOT NULL,
    InvCode VARCHAR(8) NOT NULL,
    Email_Confirmed BIT DEFAULT 0 NOT NULL,
    Account_Status BIT DEFAULT 0 NOT NULL,
    FOREIGN KEY (AddressID) REFERENCES Address(AddressID)
);

CREATE TABLE IF NOT EXISTS user_business
(
    UserID VARCHAR(128) NOT NULL,
    BusinessID VARCHAR(128) NOT NULL,
    privilege BIT DEFAULT 0 NOT NULL, -- 0 = staff, 1 = admin
    PRIMARY KEY (UserID, BusinessID),
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
    FOREIGN KEY (BusinessID) REFERENCES Business(BusinessID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Password
(
    UserID VARCHAR(128),
    BusinessID VARCHAR(128),
    Password VARCHAR(64) NOT NULL,
    Salt VARCHAR(64) NOT NULL,
    PRIMARY KEY (UserID, BusinessID),
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
    FOREIGN KEY (BusinessID) REFERENCES Business(BusinessID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Address
(
    AddressID VARCHAR(128) NOT NULL UNIQUE PRIMARY KEY,
    Line1 VARCHAR(128) NOT NULL,
    Line2 VARCHAR(128) NOT NULL,
    City VARCHAR(128) NOT NULL,
    Postcode VARCHAR(128) NOT NULL
    
);

CREATE TABLE IF NOT EXISTS Review 
(
    BusinessID VARCHAR(128) NOT NULL,
    ReviewerID VARCHAR(128) NOT NULL,
    PurchaseID VARCHAR(128) NOT NULL,
    Rating INT NOT NULL,
    Review TEXT NOT NULL,
    Date INT NOT NULL,
    PRIMARY KEY (BusinessID, ReviewerID, PurchaseID, Date)
    FOREIGN KEY (BusinessID) REFERENCES Business(BusinessID) ON DELETE CASCADE
    FOREIGN KEY (ReviewerID) REFERENCES User(UserID) ON DELETE CASCADE
    FOREIGN KEY (PurchaseID) REFERENCES Purchase(PurchaseID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Listing
(
    ListingID VARCHAR(128) NOT NULL UNIQUE,
    Name VARCHAR(128) NOT NULL,
    Desc TEXT NOT NULL,
    Price DECIMAL(10,2) NOT NULL,
    img TEXT,
    Quantity INT NOT NULL,
    CategoryID VARCHAR(128) NOT NULL,
    SellerID VARCHAR(128) NOT NULL,
    SDate TEXT NOT NULL,
    EDate TEXT NOT NULL,
    Status BIT DEFAULT 0 NOT NULL, -- 0 = active, 1 = Expired
    PRIMARY KEY (ListingID)
    FOREIGN KEY (CategoryID) REFERENCES Catergories(CatergoryID) ON DELETE CASCADE
    FOREIGN KEY (SellerID) REFERENCES Business(BusinessID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Purchase
(
    PurchaseID VARCHAR(128) NOT NULL UNIQUE,
    ListingID VARCHAR(128) NOT NULL,
    BuyerID VARCHAR(128) NOT NULL,
    Date INT NOT NULL,
    Quantity INT NOT NULL,
    Code VARCHAR(4) NOT NULL,
    PRIMARY KEY (PurchaseID)
    FOREIGN KEY (ListingID) REFERENCES Listing(ListingID) ON DELETE CASCADE
    FOREIGN KEY (BuyerID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Catergories
(
    CatergoryID VARCHAR(128) NOT NULL UNIQUE,
    Name VARCHAR(128) NOT NULL UNIQUE,
    PRIMARY KEY (CatergoryID)
);
